name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies
        run: uv sync

      - name: Lint (black/isort check)
        run: |
          uv run black --check src/
          uv run isort --check-only src/

      - name: Type check (mypy)
        run: uv run mypy src/

      - name: Run tests
        run: uv run pytest -q

